cat(R.version.string, "\n")
library(limma)
cat("limma", as.character(packageVersion("limma")), "\n")
set.seed(1)
y <- matrix(rnorm(100 * 6), 100)
design <- model.matrix(~0 + factor(c(1, 1, 1, 2, 2, 2)))
fit <- lmFit(y, design)
fit2 <- eBayes(fit, robust = TRUE, trend = TRUE)
cat("eBayes smoke OK, topTable rows:", nrow(topTable(fit2, number = 5)), "\n")
